demo/demo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.shortcuts import render
from material.models import Material
import datetime


from django.views.static import serve

from .settings import  STATIC_ROOT


def index(request):
    a = Material.objects.all().count()
    if a <16:
        material_list = Material.objects.all()
    else:
        material_list = Material.objects.all()[a-15:a]
    news = Material.objects.filter(id=a).first()

    now_time = datetime.datetime.now().strftime('%Y-%m-%d')
    yes_all = Material.objects.filter(is_match=True).count()
    no_all = a - yes_all
    if a != 0:
        p_all = str(yes_all/a*100)[:4] + '%'
    else:
        p_all = "0 %"

    all_today = Material.objects.filter(add_date=now_time).count()
    yes_today = Material.objects.filter(is_match=True,add_date=now_time).count()
    no_today = all_today - yes_today
    if all_today != 0:
        p_today = str(yes_today /all_today*100)[:4] + '%'
    else:
        p_today = "0 %"
    number_data = [yes_all,no_all,yes_today,no_today,p_all,p_today]
    return render(request,'index.html',{'list':material_list,'username':request.session.get('name'),'news':news,'number_data':number_data})

def help(request):
    return render(request,'help.html',{'username':request.session.get('name')})


# def test(request):
#     return render(request,'test.html')


def map(request):
    return render(request,'map_origin.html')

def picture(request):
    return render(request,'day_public_match.html')

from function.pathdraw import distance3,solve,find_fuc
from pyecharts import options as opts
from pyecharts.charts import Map3D
from pyecharts.globals import ChartType

def data_tranfer(x):
    jingdu = []
    weidu = []
    for citt in x:
        jingdu.append(float(citt[2]))
        weidu.append(float(citt[3]))
    jingweidu = list(zip(jingdu, weidu))
    # print(jingweidu)
    example_data = [[jingweidu[i], jingweidu[i + 1]] for i in range(len(jingweidu) - 1)]
    # print(example_data)
    c = (
        Map3D()
            .add_schema(

            itemstyle_opts=opts.ItemStyleOpts(
                color="rgb(5,101,123)",
                opacity=1,
                border_width=0.8,
                border_color="rgb(62,215,213)",
            ),
            light_opts=opts.Map3DLightOpts(
                main_color="#fff",
                main_intensity=1.2,
                is_main_shadow=False,
                main_alpha=55,
                main_beta=10,
                ambient_intensity=0.3,
            ),
            view_control_opts=opts.Map3DViewControlOpts(center=[-10, 0, 10]),
            post_effect_opts=opts.Map3DPostEffectOpts(is_enable=False),
        )
            .add(
            series_name="",
            data_pair=example_data,
            type_=ChartType.LINES3D,
            effect=opts.Lines3DEffectOpts(
                is_show=True,
                period=0.6,
                trail_width=7.6,
                trail_length=1.8,
                trail_color="#f00",
                trail_opacity=1,
            ),
            linestyle_opts=opts.LineStyleOpts(is_show=False, color="#fff", opacity=0),
        )
            .set_global_opts(title_opts=opts.TitleOpts(title="路径规划可视化"))
            .render("templates/routeline.html")
    )



def pathdraw(request,m_id):
    mym = Material.objects.get(id=m_id)
    myobj = mym.user
    othermobj = Material.objects.get(id=mym.match_id)
    otherobj = othermobj.user
    an = myobj.address.split(' ')[1]
    bn = otherobj.address.split(' ')[1]

    a = find_fuc(an)
    b = find_fuc(bn)
    main_list = solve(a, b)
    data_tranfer(main_list)
    print("draw map successfully")
    return render(request,'routeline.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('index/',index,name='index'),
    path('material/',include('material.urls')),
    path('help/',help,name='help'),
    # path('test/',test,name='test'),
    path('map/',map,name='map'),
    path('picture/',picture,name='picture'),
    path('',index),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    path('pathdraw/<int:m_id>/',pathdraw,name='pathdraw'),
]

demo/material/urls.py
from django.urls import path,include
from django.shortcuts import render

from . import views

app_name = 'material'

urlpatterns = [
    path('add_new/',views.add_new,name='add_new'),
    path('edit_m/<int:edit_id>/',views.edit_m,name='edit_m'),
    path('check/<int:check_id>/',views.check,name='check'),
    path('search_type/',views.search_type,name='search_type'),
    path('search_is_hospital/',views.search_is_hospital,name='search_is_hospital'),
    path('match/<int:m_id>/',views.match,name='match'),
    path('rematch/<int:m_id>/',views.rematch,name='rematch'),
    path('match_list/<int:user_id>/',views.match_list,name='match_list'),
]

demo/user/urls.py
from django.urls import path,include
from . import views

#应用命名空间
app_name = 'user'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('home/',views.home,name='home'),
    path('logout/',views.logout,name='logout'),
    path('edit_info/<int:user_id>/', views.edit_info, name='edit_info'),
    path('user_info/<int:user_id>/',views.user_info,name='user_info'),
    path('test_password/<int:user_id>/',views.test_password,name='test_password'),
    path('picture/<int:user_id>/',views.picture,name='picture'),
    path('test/',views.test,name='test'),

]

demo/user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=256)
    phone_number = models.CharField(max_length = 12)
    address = models.CharField(max_length=256)
    linkman = models.CharField(max_length=5)
    is_hospital = models.BooleanField(default=True)
    last_login = models.DateField(auto_now=True)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>风月同天</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css"/>
  <script src="/static/plugins/bootstrap-3.3.7-dist/js/jquery.min.js"></script>
<script src="/static/plugins/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/bitbug_favicon1.ico">
    <script>
$(function () {
	$("[data-toggle='popover']").popover({html:true,delay:{ show: 500, hide: 3000 }});
});
</script>
    {% block css %}
    {% endblock css %}
  <style>
    body{
    postition:sticky;
    top:0px;right:0;left:0;
    }
	@font-face{
    font-family:myfont;
    src:url(../static/plugins/font/myfont.TTF)
    }
  </style>
</head>
<body>
<!--background-image: linear-gradient(to right, #0099ff , #99ccff);-->
<nav class="navbar navbar-default navbar-fixed-top" style="background:rgba(0,0,0,0.7);border:0;margin-bottom:auto;font-family: myfont;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}" style="color:#ffffff;"><span style="font-size:28px;">风月同天</span><small>医疗物资智能分配平台</small></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="font-size: 17px;">
      <ul class="nav navbar-nav nav-tabs">
          <li role="presentation"><a href="{% url 'index' %}" style="color:#ffffff;">物资大厅 </a></li>
          <li role="presentation"><a href="{% url 'user:home' %}" style="color:#ffffff;">个人中心 </a></li>
          <li role="presentation"><a href="{% url 'help' %}" style="color:#ffffff;">关于平台 </a></li>
<!--        <li class="dropdown">-->
<!--          <ul class="dropdown-menu">-->
<!--            <li><a href="#">Action</a></li>-->
<!--            <li><a href="#">Another action</a></li>-->
<!--            <li><a href="#">Something else here</a></li>-->
<!--            <li role="separator" class="divider"></li>-->
<!--            <li><a href="#">Separated link</a></li>-->
<!--            <li role="separator" class="divider"></li>-->
<!--            <li><a href="#">One more separated link</a></li>-->
<!--          </ul>-->
<!--        </li>-->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if username == None %}
        <li><img src="/static/images/background1.png" style="width:30px;height:30px;margin-top:10px;margin-right:60px;padding:0;border:0px solid #99CCFF;border-radius:15px;"
                 title="<h5>用户未登录</h5>" data-trigger="hover"
			data-container="body" data-toggle="popover" data-placement="bottom" data-content="<a href='{% url 'user:register' %}' role='label' class='label label-info'>注册</a> <a href='{% url 'user:login'%}' role='label' class='label label-info'>登录</a>"/></li>
        {% else %}
        <li><img src="/static/images/background1.png" style="width:30px;height:30px;margin-top:10px;margin-right:60px;padding:0;border:0px solid #99CCFF;border-radius:15px;"
                 title="<h6><b>你好:{{username}}</b></h6>" data-trigger="hover"
			data-container="body" data-toggle="popover" data-placement="bottom" data-content="<a href='{% url 'user:home' %}' role='label' class='label label-info'>个人中心</a> <a href='{% url 'user:logout'%}' role='label' class='label label-info'>退出</a>"/></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container" id="content" style="margin-top:0px;">
    {% block content %}{% endblock content %}
</div>

{% block special %}{% endblock special %}


{% block js %}{% endblock js %}


  <!-- <div style="clear:both;background-color:#6495ED;padding-top:150px;text-align:center;color:#f0ffff;">
    <p>Copyright ©风月同天 2020 All Rights Reserved.</p>
    <a>建议</a><a>反馈</a>
  </div>
 -->
</body>

</html>

demo/templates/help.html
{% extends 'base.html' %}

{% block special %}

<div style="padding-top:50px;padding-bottom:20px;background-image:url('/static/images/background1.png');background-repeat:no-repeat;background-attachment:fixed;">


    <div class="panel panel-default" style="background-color:transparent;border:0;width:1000px;margin-left:250px;margin-top:100px;height:850px;text-align:center;">
    <div class="panel-heading" style="background:rgba(55,254,253,0.3);text-align:left;"><div style="opacity:1;color:#ffffff;font-size:20px;letter-spacing:5px;">使用帮助</div></div>
<div class="panel-body" style="padding:0px;">
    <div style="background-color:transparent;background:rgba(0,0,0,0.7);color:#ffffff;opacity:1;background-image:url('/static/images/help3.png');background-repeat:no-repeat;height:800px;width:1000px;">

</div>
  </div>
</div>


</div>



{% endblock special %}

demo/templates/index.html
{% extends 'base.html' %}

{% block special %}

<script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>




<div style="padding-top:50px;background-image:url('/static/images/background1.png');padding-bottom:20px;background-repeat:no-repeat;background-attachment:fixed;">
<div class="panel panel-default" style="border:0;background-color:transparent;margin:auto;margin-left:200px;width:1200px;margin-top:0px;height:50px;">
  <div class="panel-body" style="text-align:center;font-size:18px;color:#ffffff;letter-spacing:5px;">
    最新发布    {{ news.user.name }}发布了{{ news.mname }}*{{ news.number }}
  </div>
</div>
<!--<hr style="FILTER:alpha(opacity=100,finishopacity=0,style=3)" width="95%" color="#F8F8F8" size="10">-->

<div>
<div style="background:rgba(0,0,0,0.8);color:#ffffff;opacity:1;box-shadow:0 0 10px gray;border-radius:10px;margin:auto;margin-top:30px;margin-left:100px;width:800px;height:530px;float:left;overflow:hidden;">
    <iframe src="{% url 'map' %}" frameborder="0" width="790" height="600"></iframe>
</div>

</div>

<!--<hr style="FILTER:alpha(opacity=100,finishopacity=0,style=3)" width="95%" color="#F8F8F8" size="10">-->


<div style="background-color:transparent;border:0;text-align:center;margin-top:30px;float:left;margin-left:50px;" class="panel panel-default">
    <div class="panel-heading" style="background:rgba(55,254,253,0.3);text-align: left;"><div style="color:#ffffff;opacity:1;font-size:20px;letter-spacing:5px;"><span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> 匹配总览</div></div>
<!--    <div class="panel-body">-->
    <table class="table table-info" style="width:450px;background-color:#000000;opacity:0.8;color:#ffffff;">
<!--        <tr>-->
<!--            <th colspan="6" style="text-align:center;">匹配总览</th>-->
<!--        </tr>-->
        <tr>
            <td colspan="2">总匹配率:{{ number_data.4 }}</td>
            <td colspan="2">总匹配条数:{{ number_data.0 }}</td>
            <td colspan="2">待匹配条数:{{ number_data.1 }}</td>
        </tr>
        <tr>
            <td colspan="2">今日匹配率:{{ number_data.5 }}</td>
            <td colspan="2">今日匹配条数:{{ number_data.2 }}</td>
            <td colspan="2">今日待匹配条数:{{ number_data.3 }}</td>
        </tr>
    </table>
<!--    </div>-->
</div>

<div class="panel panel-default" style="background-color:transparent;border:0;width:450px;margin-left:950px;margin-top:200px;height:200px;text-align:center;">
    <div class="panel-heading" style="background:rgba(55,254,253,0.3);text-align: left;"><div style="opacity:1;color:#ffffff;font-size:20px;letter-spacing:5px;"><span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>  相关资讯</div></div>
    <div class="panel-body" style="background-color:#000000;opacity:0.8;color:#ffffff;padding-bottom:0;">
        <h3>欢迎来到风月同天医疗物资分配平台</h3>
<h4 style="margin-left:5px;text-align: left;letter-spacing: 5px;"><a href="https://ncov.dxy.cn/ncovh5/view/pneumonia?from=timeline"><i class="fa fa-paperclip" aria-hidden="true"></i>全国新冠肺炎疫情实时动态 </a></h4>
<h4 style="margin-left:5px;text-align: left;letter-spacing: 5px;"><a href="http://society.people.com.cn/GB/369130/431577/431608/index.html"><i class="fa fa-paperclip" aria-hidden="true"></i>疫情快讯（人民网）</a></h4>
<h4 style="margin-left:5px;text-align: left;letter-spacing: 5px;"><a href="http://www.nhc.gov.cn/xcs/xxgzbd/gzbd_index.shtml"><i class="fa fa-paperclip" aria-hidden="true"></i>疫情防控（宣传司） </a></h4>
<h4 style="margin-left:5px;text-align: left;letter-spacing: 5px;"><a href="http://news.cntv.cn/special/reci/dgr/index.shtml"><i class="fa fa-paperclip" aria-hidden="true"></i>疫情新闻频道</a></h4>
<h4 style="margin-left:5px;text-align: left;letter-spacing: 5px;"><a href="https://www.guancha.cn/xinguan?s=syztbq"><i class="fa fa-paperclip" aria-hidden="true"></i>观察者网:新冠肺炎抗疫战</a></h4>

	
	</div>
</div>



<!--FILTER:alpha(opacity=100,finishopacity=0,style=3)-->
<div style="margin-top:0px;">
<hr style="background:rgba(0,0,0,0.8);margin-bottom:0px;margin-top:0px;" width="95%" color="#F8F8F8" size="10">
</div>

<div style="float:left;color:rgba(55,254,253,0.3);margin-left:10px;"><h3 style="margin-top:0px;"><span class="glyphicon glyphicon-bookmark" aria-hidden="true"><span style="color:#ffffff;opacity:0.8;">物资一览</span></span></h3></div>
<div style="float:left;margin-bottom:20px;margin-left:300px;margin-top:20px;">
<form method="post" action="{% url 'material:search_type' %}" class="form-inline">
    {% csrf_token %}
    <div class="form-group">
    <label for="type" style="color:#ffffff;">物资类型:</label>
    <select name="search_type" id="type" class="form-control">
    <option hidden></option>
    <option value="防护服">防护服</option>
    <option value="口罩">口罩</option>
    <option value="呼吸机">呼吸机</option>
    <option value="护目镜">护目镜</option>
    <option value="血袋">血袋</option>
    <option value="药品">药品</option>
    </select>
    </div>
    <button type="submit" class="btn btn-info" style="margin-left:5px;background-color:transparent;border:0;background:rgba(55,254,253,0.5);">搜索</button>

</form>
</div>

<div style="float:left;margin-left:100px;margin-bottom:20px;margin-top:20px;">
<form method="post" action="{% url 'material:search_is_hospital' %}" class="form-inline">
    {% csrf_token %}
    <div class="form-group">
    <label for="usertype" style="color:#ffffff;">单位类型:</label>
    <select name="search_is_hospital" id="usertype" class="form-control">
    <option hidden></option>
    <option value="True">医院</option>
    <option value="False">物资供应方</option>
    </select>
    </div>
    <button type="submit" class="btn btn-info" style="margin-left:5px;background-color:transparent;border:0;background:rgba(55,254,253,0.5);">搜索</button>
</form>
</div>

<div style="float:left;margin-left:100px;margin-bottom:20px;margin-top:20px;background-color:transparent;border:0;">
    <a role="button" class="btn btn-info" href="{% url 'index' %}" style="background-color:transparent;border:0;background:rgba(55,254,253,0.5);">返回总览</a>
</div>


<table class="table table-striped table-hover" style="background-color:transparent;text-align:center;width:1000px;margin-left:250px;margin-bottom:0px;">
    <tr style="background:rgba(55,254,253,0.3);color:#ffffff;">
        <th style="text-align:center;">是否匹配</th>
        <th style="text-align:center;">单位名称</th>
        <th style="text-align:center;">物资名称</th>
        <th style="text-align:center;">物资类别</th>
        <th style="text-align:center;">数量</th>
        <th style="text-align:center;">日期</th>
        <th style="text-align:center;">查看</th>
    </tr>
{% for i in list %}
    <tr style="background-color:transparent;background:rgba(0,0,0,0.8);color:#ffffff;">
        {% if i.is_match == True %}
        <td><span class="glyphicon glyphicon-ok" aria-hidden="true" style="color:#33CC33;"></span></td>
        {% else %}
        <td><span class="glyphicon glyphicon-time" aria-hidden="true" style="color:#FF9933;"></span></td>
        {% endif %}
        <td>{{i.user.name}}</td>
        <td>{{i.mname}}</td>
        <td>{{i.type}}</td>
        <td>{{i.number}}</td>
        <td>{{i.add_date}}</td>
        <td><a href="{% url 'material:check' i.id %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>查看</a></td>
    </tr>
{% endfor %}
    <tr style="background-color:transparent;background:rgba(0,0,0,0.8);color:#ffffff;">
        <td>...</td>
        <td>...</td>
        <td>...</td>
        <td>...</td>
        <td>...</td>
        <td>...</td>
        <td>...</td>

    </tr>
</table>

  <div style="clear:both;background-color:transparent;padding-top:100px;padding-bottom:0;text-align:center;color:#ffffff;">
    <h4>Copyright ©风月同天 2020 All Rights Reserved.</h4>
    <a data-toggle="modal" data-target="#myModal4">建议&反馈</a>

<!-- Modal -->
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" style="color:#000000;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel4">建议&反馈</h4>
      </div>
      <div class="modal-body">
        欢迎发邮件至:1652123586@qq.com提供您的宝贵建议和使用反馈，我们将不胜感激！
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>
	
	
	
	
  </div>

</div>



{% endblock special %}

demo/templates/register.html
{% extends 'base.html' %}



{% block special %}
<div style="background-image:url('/static/images/background1.png');margin:auto;padding-top:70px;">

    <div class="panel panel-default" style="text-align:center;background-color:transparent;border:0px;width:750px;height:700px;margin:auto;
padding-left:95px;padding-right:95px;padding-top:50px;padding-bottom:50px;">
  <div class="panel-heading" style="border:0;background:rgba(55,254,253,0.3);text-align:left;color:#ffffff;opacity:1;font-size:20px;letter-spacing:5px;">用户注册</div>
  <div class="panel-body" style="background:rgba(0,0,0,0.7);text-align:center;color:#ffffff;opacity:1;">


      <form method="post" action="{% url 'user:register' %}" role="form">

    {% csrf_token %}

<div class="form-group" style="text-align:left;">
        <label for="id_name">用户名:(若为医院打勾)</label>
    <div class="row">
    <div class="col-md-10" style="padding-right:0;">
        <input type="text" name="name" maxlength="20" required="" id="id_name" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">
    </div>
        <div class="col-md-2" style="padding-left:0;">
        <input type="checkbox" name="is_hospital" id="id_is_hospital" checked="" class="form-control" style="margin-top:0;border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">
        </div>
    </div>
</div>
    <div class="form-group" style="text-align:left;">
        <label for="id_password">密码:</label>
        <input type="password" name="password" maxlength="256" required="" id="id_password" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">

    </div>
    <div class="form-group" style="text-align:left;">
        <label for="id_password2">确认密码:</label>
        <input type="password" name="password2" maxlength="256" required="" id="id_password2" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">

    </div>
    <div class="form-group" style="text-align:left;">
        <label for="id_phone_number">联系电话:</label>
        <input type="text" name="phone_number" maxlength="12" required="" id="id_phone_number" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">

    </div>

    <script src="/static/plugins/js/address.js"></script>

    <div class="form-group" style="text-align:left;">
    <label>地址:</label>
     <select name="province" id="province" onChange="set_city()" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">
    <option value="none" style="">选择省</option>
<script>
  for(var i=0;i<provinceArr.length;i++){
  document.write('<option style="background:rgba(256,256,256,256,0.6);color:#000000;" value="'+i+'">'+provinceArr[i]+'</option>');
  }
</script>
    </select>

    <select name="city" id="city" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">
    <option value="none" style="">选择城市</option>
    </select>
    </div>

   <div class="form-group" style="text-align:left;">
        <label for="id_linkman">联系人:</label>
        <input type="text" name="linkman" maxlength="5" required="" id="id_linkman" class="form-control" style="border:0;background-color:transparent;background:rgba(256,256,256,0.6);color:#ffffff;opacity:1;">

    </div>


    <button type="submit" class="btn btn-info btn-lg" style="border:0;background:rgba(55,254,253,0.5);text-align:center;color:#ffffff;opacity:1;">提交</button>{{msg}}
</form>



  </div>
    </div>

</div>


{% endblock special %}

demo/templates/user_info.html
{% extends 'homebase.html' %}

{% block css %}
<script>
    window.onload = function(){
    var s1 = document.getElementById("s4");
    s1.style.color = "rgba(55,254,253)";
    }
</script>
{% endblock css %}


{% block special %}

{% if passworderror %}
<button id="passworderror" style="margin-left:450px;margin-top:20px;opacity:0.8;" class="btn btn-danger">{{passworderror}}</button>
<script>

setTimeout(function(){document.getElementById("passworderror").style.display="none";},3000);

</script>
{% endif %}

<div style="float:left;">
<ul class="list-group" style="margin-left:250px;margin-top:130px;text-align:center;width:600px;">
  <li class="list-group-item list-group-item-info" style="background-color:transparent;border:0;background:rgba(55,254,253,0.3);text-align: left;"><span style="color:#ffffff;opacity:1;font-size:18px;letter-spacing:5px;">账户信息</span></li>
  <li class="list-group-item" style="background-color:#000000;opacity:0.8;color:#ffffff;">用户名:{{ user.name }}</li>
  <li class="list-group-item" style="background-color:#000000;opacity:0.8;color:#ffffff;">地址:{{ user.address }}</li>
  <li class="list-group-item" style="background-color:#000000;opacity:0.8;color:#ffffff;">联系人:{{ user.linkman }}</li>
  <li class="list-group-item" style="background-color:#000000;opacity:0.8;color:#ffffff;">联系电话:{{ user.phone_number }}</li>
</ul>

<!--<a role="button" class="btn btn-success btn-lg" href="{% url 'user:edit_info' user.id %}" style="margin-left:600px;margin-top:20px;">修改信息</a>-->

<div style="margin-left:600px;margin-top:20px;">
    <a role="button" class="btn btn-success btn-lg" style="text-align:center;margin:45px;background-color:transparent;border:0;background:rgba(55,254,253,0.5);"
        data-toggle="modal" data-target="#myModal2">修改信息</a>
<!--href="{% url 'material:add_new' %}"-->
    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel2" style="text-align:center;">
					修改信息需要输入密码
				</h4>
			</div>

			<div class="modal-body">
<form id="form2" role="form" method="post" action="{% url 'user:test_password' user.id %}">
    {% csrf_token %}
    <div class="form-group">
                    <label for="password_first">账户密码:</label>
                    <input type="password" name="password_first" id="password_first" class="form-control" maxlength="30" required placeholder="请输入账户密码"/>
                    </div>

</form>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-danger btn-lg"
						data-dismiss="modal">
					<span class="glyphicon glyphicon-home" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-info btn-lg" onclick="submit2()">
					<span class="glyphicon glyphicon-send" aria-hidden="true"></span>
				</button>
			</div>
		</div><!-- /.modal-content -->

<script>
    function submit2()
    {

   document.getElementById("form2").submit();
    }
</script>


	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


</div>
</div>
{% endblock special %}